name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - env:
          CC: ${{ matrix.compiler }}
        run: make test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test
